import './screens/register.js'
import './inputWrapper.js'
import './screens/login.js'
import {getItemFromLocalStorage} from './utils.js'
import './screens/story.js'
import './header.js'
import './createPost.js'
import './postItem.js'
import './listPost.js'
import './navigo.js'
